browser=chrome
headless=false

Baseurl=https://www.ndosiautomation.co.za

Imagepath="C:\Users\USER\OneDrive\Desktop\NdosiFrameworkFinalProject\src\main\resources\Profile.jpg"

ui.base.url=https://ndosisimplifiedautomation.vercel.app/

DB_URL="jdbc:mysql://102.222.124.22:3306/ndosian6b8b7_teaching";

DB_USERNAME="ndosian6b8b7_teaching";
DB_PASSWORD="^{SF0a=#~[~p)@l1";



username=testuser
password=testpassword